name: LinkedIn Cards

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-linkedin-cards:
    uses: ./.github/workflows/linkedin-cards.yml
    with:
      apify_api_token: ${{ secrets.APIFY_API_TOKEN }}
      linkedin_username: ${{ vars.lyestk }}
      max_cards_to_generate: 4
      language: en
